// hlg-vue/src/views/Index/Gwc.vue
<script>
import * as service from "@/api/index";
import MyNavBar from "@/components/MyNavBar.vue";
import { showLoadingToast, showToast } from "vant";
export default {
  components: { MyNavBar },
  data() {
    return {
      cartlist: [],
      show: false,
    };
  },
  async mounted() {
    this.updata();
  },
  methods: {
    async queren() {
      var res = await service.removeall({ userid: this.$store.state.Userid });
      this.updata();
    },
    //点击清空，弹出确认框
    clearCart() {
      this.show = true;
    },
    //点击提交
    onSubmit() {
      showToast("下单");
    },
    //更新数据
    async updata() {
      showLoadingToast({ message: "加载中...", forbidClick: true });
      var res = await service.cartlist({ userid: this.$store.state.Userid });
      this.cartlist = res.data.data || [];
    },
    async check(id, flag) {
      //改变状态
      var res = await service.selectone({ cartid: id, flag: !flag });
      this.updata();
    },
    //加号
    async jiaNum(id, num) {
      var res = await service.updatenum({ cartid: id, num: ++num });
      this.updata();
    },
    //减号
    async jianNum(id, num) {
      if (num > 1) {
        var res = await service.updatenum({ cartid: id, num: --num });
        this.updata();
      }
    },
  },
  computed: {
    //总价
    sumPrice() {
      return (
        this.cartlist
          .filter((item) => item.flag)
          .reduce((prev, item) => (prev += item.num * item.originprice), 0) *
        100
      );
    },
    //全选
    isAll: {
      get() {
        if (this.cartlist.length) {
          return this.cartlist.every((item) => item.flag);
        }
      },
      async set(val) {
        var res = await service.selectall({
          userid: this.$store.state.Userid,
          type: val,
        });
        this.updata();
      },
    },
  },
};
</script>
<template>
  <div class="gwc">
    <MyNavBar title="购物车" rightText="清空" @click="clearCart" />
    <van-dialog
      v-model:show="show"
      title="清空购物车所有商品?"
      show-cancel-button
      @confirm="queren"></van-dialog>
    <div class="context">
      <div class="good" v-for="cartitem in cartlist" :key="cartitem.cartid">
        <div class="check">
          <van-checkbox
            :checked="cartitem.flag"
            @click="check(cartitem.cartid, cartitem.flag)"></van-checkbox>
        </div>
        <div class="img_box"><img :src="cartitem.img1" alt="" /></div>
        <div class="text">
          <h3>{{ cartitem.proname }}</h3>
          <div class="price">￥{{ cartitem.originprice }}</div>
        </div>
        <div class="btns">
          <button @click="jianNum(cartitem.cartid, cartitem.num)">-</button>
          <span>{{ cartitem.num }}</span>
          <button @click="jiaNum(cartitem.cartid, cartitem.num)">+</button>
        </div>
      </div>
    </div>
    <van-submit-bar :price="sumPrice" button-text="提交订单" @submit="onSubmit">
      <van-checkbox v-model="isAll">全选</van-checkbox>
    </van-submit-bar>
  </div>
</template>
<style scoped>
h3 {
  font-weight: normal;
}

.gwc {
  height: 100%;
  display: flex;
  flex-direction: column;
}

.gwc .context {
  flex: 1;
  overflow-y: auto;
  margin-bottom: 0.3125rem;
}

.gwc .context .check {
  margin-right: 10px;
}

.gwc .context .check input {
  border-radius: 50%;
  width: 15px;
  height: 15px;
}

.gwc .context .good {
  display: flex;
  align-items: center;
  margin: 0 10px 10px;
  padding: 10px;
  box-sizing: border-box;
  background: #eee;
  border-radius: 10px;
  position: relative;
}

.gwc .good .img_box {
  width: 0.25rem;
}

.gwc .good .img_box img {
  width: 0.225rem;
  height: 0.225rem;
  border-radius: 5px;
}

.gwc .good .text {
  font-size: 12px;
  flex: 1;
}

.gwc .good .text h3 {
  font-size: 13px;
  text-align: left;
}

.gwc .good .text .price {
  margin: 20px 0 0;
  font-size: 16px;
  color: #f66;
}

.gwc .good .btns {
  position: absolute;
  right: 10px;
  bottom: 10px;
}

.gwc .good .btns button {
  padding: 5px 10px;
  box-sizing: border-box;
  background: #fff;
  border: 1px solid #ccc;
  border-radius: 5px;
  font-size: 12px;
}

.gwc .good .btns button:hover {
  background: #eee;
}

.gwc .good .btns span {
  margin: 0 5px;
}

.van-submit-bar {
  margin-bottom: 50px;
}
</style>

// hlg_react/src/views/Index/Gwc/index.tsx
import React, { PureComponent } from 'react';
import TopNav from '@/components/TopNav';
import './index.scss'
import {cart_list,cart_selectone,cart_selectAll,cart_updatenum,cart_removeall} from '@/api'
import {Button,Dialog,Toast} from 'antd-mobile'
import {connect} from 'react-redux'

interface PropsType {
    history:any,
    location:any,
    match:any,
    userid:string
}
interface stateType{
    data:any,
}

class Gwc extends PureComponent<PropsType,stateType> {
    constructor(props:PropsType){
        super(props)
        this.state = {
            data:[],
        }
    }
    //挂载并获取数据
    componentDidMount() {
        this.updata();
    }
    //更新数据
    async updata(){
        Toast.show({
            icon: 'loading',
            content: '加载中',
            duration: 0,
          })
        let userid = this.props.userid
        var res = await cart_list({userid});
        res.data.code == 10020 && this.setState({data:[]})
        res.data.code == 200 && this.setState({data:res.data.data})
        Toast.clear()
    }
    //点击单选
    async handleCheck(obj:{}){
        var res = await cart_selectone(obj)
        res.data.code == 200 && this.updata();
    }
    //点击减号
    async handleJian(obj:{num:number,cartid:string}){
        obj.num = obj.num<=1? 1:--obj.num;
        var res = await cart_updatenum(obj);
        res.data.code == 200 && this.updata();
    }
    //点击加号
    async handleJia(obj:{num:number,cartid:string}){
        obj.num++;
        var res = await cart_updatenum(obj);
        res.data.code == 200 && this.updata();
    }
    //总价
    priceAll(){
        return this.state.data.filter((item:any)=>item.flag).reduce((prev:number,item:any)=> prev+item.originprice * item.num,0);
    }
    //全选
    checkAll(){
        if(!this.state.data.length) return false;//购物车为空则不全选
        return this.state.data.every((item:any)=>item.flag)
    }
    //点击全选
    async handleCheckAll(type:boolean){
        if( this.state.data.length <= 0 ) return
        var res = await cart_selectAll({userid:this.props.userid,type});
        res.data.code == 200 && this.updata();
    }
    //清空购物车
    async deleteCart(){
        if( this.state.data.length <= 0 ) return
        Dialog.confirm({
            content: '是否清空购物车',
        }).then(async (res)=>{
            if(res){
                let res = await cart_removeall({userid:this.props.userid});
                res.data.code == 200 && await this.updata();
                Toast.show({
                    icon: 'success',
                    content: '清空成功',
                    position: 'bottom',
                })
            }
        })    
    }

    //点击提交订单
    goBuy(priceAll:number){
        if( this.state.data.length <= 0 ){
            Dialog.show({
                content: `请先选择商品`,
                closeOnAction: true,
                actions:[
                    { key: '2',text: '确认',}
                ],
                onAction: action => action.key == 2 && this.props.history.push('/index/home') 
            },)
        }else{
            let userid = this.props.userid
            Dialog.show({
                content: `需要支付${priceAll}元`,
                closeOnAction: true,
                actions:[
                    { key: '0',text: '去支付',},
                    { key: '1',text: '取消',}
                ],
                onAction: action => {
                    action.key == 0 && Toast.show({
                        content: '支付成功',
                        //支付成功则清空购物车
                        afterClose: async () => {
                            let res = await cart_removeall({userid});
                            res.data.code == 200 && await this.updata();
                        },
                     })
                }
            })
        }
    }
    render() {
        return (
            <div className='gwc'>
                  <TopNav title='购物车' flag={false}>   
                    <Button className='deleteBtn' block onClick={()=>{this.deleteCart()}}>
                        清空
                    </Button>
                </TopNav>
                  {!this.state.data.length && <div className="no-cart">
                        <img src="" alt="" />
                        <div className='text'>购物车空空如也</div>
                        <Button onClick={()=>{this.props.history.push('/index/home')}} color='primary'>去逛逛</Button>
                    </div>}
                  {
                    !!this.state.data.length && (<div className="gwc-list">
                    {this.state.data.map((item:any,index:number)=>{
                      return (
                         <div className="item" key={index}>
                             <input type="checkbox" name="check" checked={item.flag} onChange={()=>{this.handleCheck({cartid:item.cartid,flag:!item.flag})}}/>
                             <div className="center">
                                 <div className="left">
                                     <img src={item.img1} alt="" />
                                 </div>
                                 <div className="right">
                                     <h4>{item.proname}</h4>
                                     <div className="price">￥{item.originprice}</div>
                                 </div>
                             </div>
                             <div className="btns">
                                 <button onClick={()=>{this.handleJian({cartid:item.cartid,num:item.num})}}>-</button>
                                 <span>{item.num}</span>
                                 <button onClick={()=>{this.handleJia({cartid:item.cartid,num:item.num})}}>+</button>
                             </div>
                         </div>
                      )
                    })}
                   </div>)
                  }
                  <div className="submit-bar">
                    <div className="left">
                            <input type="checkbox" name="checkAll" checked={this.checkAll()} id='all' onChange={()=>{this.handleCheckAll(!this.checkAll())}}/>
                            <label htmlFor="all">全选</label>
                    </div>
                    <div className="right">
                        <div className="price">合计：<span>￥{this.priceAll()}</span></div>
                        <Button className="submit-btn" block onClick={() => {this.goBuy(this.priceAll())}}>提交订单</Button>
                    </div>
                  </div>
            </div>
        );
    }
}

export default connect(
    (state:any)=>{
        return {
            userid:state.userid
        }
    },
    (dispatch)=>{
        return {}
    }
)(Gwc);
