// hlg_react/src/views/Login/index.tsx
import './index.scss';
import React, { PureComponent } from 'react';
import TopNav from '@/components/TopNav';
import {login} from '@/api/index'
import { connect} from 'react-redux'

type propsType= {
    history:any,
    location:any,
    match:any,
    updataUser:any
}

type stateType = {
    loginname?:any,
    password?:string
}

class Login extends PureComponent <propsType,stateType>{
    constructor(props:propsType){
        super(props);
        this.state = {
            loginname:'18329972858',
            password:'Abc123'
        }
    }
    handleClick(event:{target:{name:string,value:string}}){
        this.setState({[event.target.name]:event.target.value});
    }
    async handleBtn(val:{}){
        let res = await login(val);
        if(res.data.code == 200){
            this.props.updataUser(res.data.data.token,res.data.data.userid,this.state.loginname);
            this.props.history.push('/index/home')
        }else{
            console.log('登录失败');
        }
    }
    render() {
        return (
            <div className='login'>
                <TopNav title="登录" flag={true}/>
                <div className="form">
                    <input type="text"  name='loginname' placeholder='请输入手机号/账户号/邮箱' value={this.state.loginname} onChange={(e)=>{this.handleClick(e)}}/>
                    <input type="text" name='password' placeholder='请输入密码' value={this.state.password} onChange={(e)=>{this.handleClick(e)}}/>
                    <input type="submit" value="登录" className='btn' onClick={()=>{this.handleBtn({loginname:this.state.loginname,password:this.state.password})}}/>
                </div>
                <div className='bottom'>
                    <a href="/register">手机快速注册</a>
                </div>
            </div>
        );
    }
}

export default connect(
    (state)=>{
        return {
        }
    },
    (dispatch)=>{
        return {
            //修改用户信息
            updataUser(token:any,userid:any,loginname:any){
                dispatch({type:'UPDATE_TOKEN',payload:token})
                dispatch({type:'UPDATE_USERID',payload:userid})
                dispatch({type:'UPDATE_TEL',payload:loginname})
            }
        }
    }
)(Login);

// hlg-vue/src/views/Login.vue
<script>
import * as service from "@/api/index";
import MyNavBar from "@/components/MyNavBar.vue";
export default {
  components: { MyNavBar },
  data() {
    return {
      username: "15555555551",
      password: "Abcde14",
    };
  },
  methods: {
    async onSubmit(val) {
      if (val.username.trim() && val.password.trim()) {
        var res = await service.Login({
          loginname: val.username,
          password: val.password,
        });
        if (res.data.code == 10011) console.log(res.data.message);
        if (res.data.code == 200) {
          this.$store.commit("setPhone", val.username);
          this.$store.commit("setToken", res.data.data.token);
          this.$store.commit("setUserid", res.data.data.userid);
          this.$router.push("/index/home");
        }
      } else {
        console.log("用户名或密码为输入");
      }
    },
  },
};
</script>
<template>
  <div class="login">
    <MyNavBar title="登录" :left="true" />
    <div class="from">
      <van-form @submit="onSubmit">
        <van-cell-group inset>
          <van-field
            v-model="username"
            name="username"
            placeholder="请输入手机号/账户号/邮箱" />
          <van-field
            v-model="password"
            name="password"
            type="password"
            placeholder="请输入密码" />
        </van-cell-group>
        <div style="margin: 16px">
          <van-button round block type="primary" native-type="submit"
            >登录</van-button
          >
        </div>
      </van-form>
    </div>
    <div class="other">
      <router-link to="/register">手机快速注册</router-link>
    </div>
  </div>
</template>
<style scoped>
.login {
  height: 100%;
  width: 100%;
  position: fixed;
  left: 0;
  top: 0;
  z-index: 2;
  background: #fff;
}

.login .from {
  margin: 0.0938rem 0;
}

.login .other {
  text-align: right;
  margin-right: 0.0625rem;
}
</style>
